# Proving the Singular Value Decomposition (SVD) Formula Using Numerical Analysis

This notebook provides a complete proof that any matrix $A \in \mathbb{R}^{m \times n}$ can be decomposed as $A = U \Sigma V^T$, where $U$ is an $m \times m$ orthogonal matrix, $\Sigma$ is an $m \times n$ diagonal matrix with non-negative singular values, and $V$ is an $n \times n$ orthogonal matrix. The proof combines linear algebra with numerical analysis principles, ensuring computational feasibility.

---

## 1. SVD Definition

The SVD of a matrix $A \in \mathbb{R}^{m \times n}$ is:
$$
A = U \Sigma V^T
$$
- **$U \in \mathbb{R}^{m \times m}$**: Orthogonal ($U^T U = UU^T = I_m$).
- **$\Sigma \in \mathbb{R}^{m \times n}$**: Diagonal, with non-negative singular values $\sigma_1 \geq \sigma_2 \geq \cdots \geq \sigma_r \geq 0$, where $r = \text{rank}(A)$.
- **$V \in \mathbb{R}^{n \times n}$**: Orthogonal ($V^T V = VV^T = I_n$).

**Goal**: Prove this decomposition exists and can be computed numerically.

---

## 2. Theoretical Foundation

The SVD is based on the eigenvalue decomposition of symmetric matrices $A^T A$ and $A A^T$.

### 2.1 Properties of $A^T A$ and $A A^T$
- **$A^T A \in \mathbb{R}^{n \times n}$** (S<sub>right</sub>): Symmetric ($(A^T A)^T = A^T A$) and positive semi-definite ($x^T (A^T A) x = \|Ax\|^2 \geq 0$).
- **$A A^T \in \mathbb{R}^{m \times m}$** (S<sub>left</sub>): Symmetric and positive semi-definite.
- **Spectral Theorem**: Both matrices have real eigenvalues and orthonormal eigenvectors.

Note: We call eigenvectors of S<sub>left</sub> the Left Singular vectors and eigenvectors of S<sub>right</sub> the Right Singular vectors.

### 2.2 Eigenvalue Connection
- Eigenvalues of $A^T A$: $\lambda_1 \geq \lambda_2 \geq \cdots \geq \lambda_n \geq 0$.
- Singular values of $A$: $\sigma_i = \sqrt{\lambda_i}$ for $i = 1, \ldots, r$, where $r \leq \min(m, n)$.
- Non-zero eigenvalues of $A^T A$ and $A A^T$ are the same.

---

## 3. Constructing the SVD

We construct $U$, $\Sigma$, and $V$ explicitly to show $A = U \Sigma V^T$.

### 3.1 Compute Eigenvectors and Eigenvalues of $A^T A$
- Form $A^T A$.
- Compute eigenvalues $\lambda_1 \geq \cdots \geq \lambda_n \geq 0$ and orthonormal eigenvectors $v_1, \ldots, v_n$.
- Singular values: $\sigma_i = \sqrt{\lambda_i}$, with $\sigma_i = 0$ for $i > r$.
- Form $V = [v_1, \ldots, v_n]$, so $V^T V = I_n$.

$$
A^T A v_i = \sigma_i^2 v_i
$$

### 3.2 Construct $U$
- For each non-zero $\sigma_i$ ($i = 1, \ldots, r$):
$$
u_i = \frac{1}{\sigma_i} A v_i
$$
- Verify orthonormality:
$$
u_i^T u_j = \frac{1}{\sigma_i \sigma_j} v_i^T A^T A v_j = \frac{1}{\sigma_i \sigma_j} v_i^T (\sigma_j^2 v_j) = \delta_{ij}
$$
- If $m > r$, extend $\{u_1, \ldots, u_r\}$ to an orthonormal basis for $\mathbb{R}^m$ using Gram-Schmidt.
- Form $U = [u_1, \ldots, u_m]$, so $U^T U = I_m$.

### 3.3 Construct $\Sigma$
- Define $\Sigma \in \mathbb{R}^{m \times n}$:
$$
\Sigma_{ij} = \begin{cases} 
\sigma_i & \text{if } i = j \leq r \\
0 & \text{otherwise}
\end{cases}
$$

### 3.4 Verify the Decomposition
- Check $A = U \Sigma V^T$:
  - For $i = 1, \ldots, r$:
    $$
    A v_i = \sigma_i u_i, \quad U \Sigma V^T v_i = U \Sigma e_i = \sigma_i u_i
    $$
  - For $i > r$, $A v_i = 0$, and $U \Sigma V^T v_i = 0$.
- Since $\{v_i\}$ is a basis for $\mathbb{R}^n$, $A = U \Sigma V^T$.

### 3.5 Orthogonality of $U$
- Alternatively, verify $u_i$ are eigenvectors of $A A^T$:
$$
A A^T u_i = A (\sigma_i v_i) = \sigma_i A v_i = \sigma_i^2 u_i
$$
- This confirms $u_i$ correspond to eigenvalues $\sigma_i^2$, ensuring consistency.

---

## 4. Numerical Computation

The SVD is computed using stable numerical algorithms.

### 4.1 QR Algorithm

It is used to measure the eigenvalues.

- **Steps**:
  1. Start with $B_0 = A^T A$.
  2. Iterate: $B_k = Q_k R_k$, $B_{k+1} = R_k Q_k$.
  3. $B_k \to \text{diagonal}(\lambda_1, \ldots, \lambda_n)$, with $V$ from accumulated $Q_k$.
- **Stability**: Orthogonal transformations ensure error $O(\epsilon \|A\|_2)$.

### 4.2 Other Methods
- **Golub-Kahan Bidiagonalization**: Reduces $A$ to bidiagonal form, then applies QR.
- **Divide-and-Conquer**: Splits matrix for efficiency, used in LAPACK.
- **Jacobi Method**: Applies rotations, suitable for parallelization.

### 4.3 Larger Matrices
- **Numerical methods**: We use numerical methods like Newton's to find solutions to equations of eigenvalues.

---

## 5. Numerical Example

Consider $A = \begin{bmatrix} 3 & 0 \\ 4 & 5 \end{bmatrix}$.

### 5.1 Compute $A^T A$
$$
A^T A = \begin{bmatrix} 25 & 20 \\ 20 & 25 \end{bmatrix}
$$

### 5.2 Eigenvalues
$$
\det(A^T A - \lambda I) = (25 - \lambda)^2 - 400 = (\lambda - 45)(\lambda - 5)
$$
- Eigenvalues: $\lambda_1 = 45$, $\lambda_2 = 5$.
- Singular values: $\sigma_1 = \sqrt{45} \approx 6.7082$, $\sigma_2 = \sqrt{5} \approx 2.2361$.

### 5.3 Eigenvectors
- For $\lambda_1 = 45$: Eigenvector $v_1 = \frac{1}{\sqrt{2}} [1, 1]$.
- For $\lambda_2 = 5$: Eigenvector $v_2 = \frac{1}{\sqrt{2}} [1, -1]$.
- Form $V = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 & 1 \\ 1 & -1 \end{bmatrix}$.

### 5.4 Compute $U$
- For $\sigma_1$:
$$
A v_1 = \frac{1}{\sqrt{2}} \begin{bmatrix} 3 \\ 9 \end{bmatrix}, \quad u_1 = \frac{1}{\sqrt{45}} \cdot \frac{1}{\sqrt{2}} \begin{bmatrix} 3 \\ 9 \end{bmatrix} = \begin{bmatrix} \frac{\sqrt{10}}{10} \\ \frac{3\sqrt{10}}{10} \end{bmatrix}
$$
- For $\sigma_2$:
$$
A v_2 = \frac{1}{\sqrt{2}} \begin{bmatrix} 3 \\ -1 \end{bmatrix}, \quad u_2 = \frac{1}{\sqrt{5}} \cdot \frac{1}{\sqrt{2}} \begin{bmatrix} 3 \\ -1 \end{bmatrix} = \begin{bmatrix} \frac{3\sqrt{10}}{10} \\ -\frac{\sqrt{10}}{10} \end{bmatrix}
$$
- Form $U = \begin{bmatrix} \frac{\sqrt{10}}{10} & \frac{3\sqrt{10}}{10} \\ \frac{3\sqrt{10}}{10} & -\frac{\sqrt{10}}{10} \end{bmatrix}$.

### 5.5 Form $\Sigma$
$$
\Sigma = \begin{bmatrix} \sqrt{45} & 0 \\ 0 & \sqrt{5} \end{bmatrix}
$$

### 5.6 Verification
- Compute $U \Sigma V^T$ and confirm it equals $A$ (can be done numerically in Python).

---

## 6. Numerical Stability
- **Condition Number**: Affects accuracy for small $\sigma_i$.
- **Error Bounds**: Algorithms achieve errors $O(\epsilon \|A\|_2)$.
- **Libraries**: LAPACK, NumPy, MATLAB use optimized implementations.

---

## 7. Conclusion
The SVD is proven because:
- **Existence**: Guaranteed by eigenvalue decomposition of $A^T A$ and $A A^T$.
- **Construction**: $V$, $U$, and $\Sigma$ are explicitly derived.
- **Verification**: $A = U \Sigma V^T$ holds for all basis vectors.
- **Numerical Feasibility**: Stable algorithms ensure practical computation.

This completes the proof. For implementation, see numerical libraries or request a Python example.

In [3]:
import numpy as np

# -----------Part 1: 2x2 Matrix A -----------
A = np.array([[4, 2],
              [1, 3]])

# Compute A^T A
ATA = A.T @ A

# Characteristic polynomial of ATA: λ^2 - trace*λ + det = 0
a = 1
b = -np.trace(ATA)
c = np.linalg.det(ATA)

# Define polynomial and derivative for Newton
def f(lmbda):
    return a * lmbda**2 + b * lmbda + c

def df(lmbda):
    return 2 * a * lmbda + b

# Newton's method
def newton_method(f, df, x0, tol=1e-10, max_iter=100):
    x = x0
    for _ in range(max_iter):
        x_new = x - f(x) / df(x)
        if abs(x_new - x) < tol:
            return x_new
        x = x_new
    raise ValueError("Did not converge")

# Use Newton's method to get eigenvalues of A^T A
lambda1 = newton_method(f, df, x0=1.0)
lambda2 = newton_method(f, df, x0=100.0)

# Singular values (via Newton)
sigma_newton = np.sort(np.sqrt([lambda1, lambda2]))[::-1]

# Singular values (via NumPy)
_, sigma_numpy, _ = np.linalg.svd(A)
sigma_numpy = np.sort(sigma_numpy)[::-1]

# Comparison
diff = np.abs(sigma_numpy - sigma_newton)

# ----------- Output -----------
print("2x2 Matrix A:")
print(A)
print("\nSingular values (Newton method):", sigma_newton)
print("Singular values (NumPy SVD):    ", sigma_numpy)
print("Difference (|NumPy - Newton|):   ", diff)

# ----------- PART 2: 3x3 Matrix with NumPy SVD -----------

B = np.array([[1, 0, 0],
              [0, 2, 0],
              [0, 0, 3]])

U, S, VT = np.linalg.svd(B)

print("\n3x3 Matrix B:")
print(B)
print("Singular values (via NumPy):", S)
print("Left singular vectors (U):\n", U)
print("Right singular vectors (V^T):\n", VT)

2x2 Matrix A:
[[4 2]
 [1 3]]

Singular values (Newton method): [5.11667274 1.95439508]
Singular values (NumPy SVD):     [5.11667274 1.95439508]
Difference (|NumPy - Newton|):    [8.8817842e-16 4.4408921e-16]

3x3 Matrix B:
[[1 0 0]
 [0 2 0]
 [0 0 3]]
Singular values (via NumPy): [3. 2. 1.]
Left singular vectors (U):
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
Right singular vectors (V^T):
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
